---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: updating apt
      command: sudo apt-get update

    - name: Install Docker
      command: sudo apt-get install -y docker.io
      args:
        warn: true
        timeout: 600  # 10 minutes (you can adjust this value as needed)
      become: yes
      become_user: root

    - name: Start Docker Service
      command: sudo systemctl start docker
      become: yes
      become_user: root

    - name: Deploy Docker Container
      command: docker run -itd -p 8084:8081 kranthi619/project1:latest



