---
- name: installing Docker in host
  hosts: server
  become: true
  tasks: 
    - name: updating server
      command: sudo apt update

    - name: install python and pip
      command: sudo apt-get install -y python-pip

    - name: remove conflicting packages
      command: sudo apt-get remove -y containerd.io runc
      ignore_errors: yes

    - name: installing docker
      command: sudo apt-get install -y docker.io
      become: yes
      become_user: root

    - name: starting docker service using systemctl
      command: sudo systemctl start docker
      become: yes
      become_user: root

    - name: Deploy Docker Container
      command: docker run -itd -p 8084:8081 kranthi619/project1:latest


